name: Build V8
description: Build for Windows x64 and Windows arm64.

on:
    schedule:
      - cron: "0 4 * * *" #Checks for release at 3 A.M.
    push:
        branches:
          - master
        paths-ignore:
          - depot_tools
          - .gitignore
          - .gitpod*
    workflow_dispatch:

jobs:
    check-release:
        name: Check for New V8 Releases
        runs-on: ubuntu-latest
        outputs:
            update: ${{steps.should_update.outputs.update}}
        steps:
          - name: Checkout This Repo
            uses: actions/checkout@v4

          - name: Get Last Built Commit
            id: current_commit
            uses: juliangruber/read-file-action@v1
            with:
                path: ./COMMIT

          - name: Checkout V8
            run: |
                cd ..
                mkdir v8
                cd v8
                git clone https://chromium.googlesource.com/v8/v8.git

          - name: Determine Should Update
            id: should_update
            run: |
                current_commit = "${{steps.current_commit.outputs.content}}"
                latest_commit = $(git rev-list --tags --max-count=1)
                if [ "$current_commit" = "$latest_commit" ]; then
                    echo "update=true" >> $GITHUB_OUTPUT
                else
                    echo "update=false" >> $GITHUB_OUTPUT
                fi

    build-win64:
        name: Windows x64
        runs-on: windows-latest
        needs: check-release
        if: needs.check-release.outputs.update == true
        steps:
          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                submodules: true
                clean: true
                fetch-depth: 1

          - name: Restore V8 Cache #I don't know why it's here
            uses: actions/cache@v4
            with:
                path: |
                    v8
                    .gclient_entries
                    .gclient_previous_sync_commits
                    .cipd
                key: ${{runner.os}}-${{runner.arch}}:libv8:v8:${{hashFiles('**/VERSION')}}
                restore-keys: |
                    ${{runner.os}}-${{runner.arch}}:libv8:v8:

          - name: Build V8
            continue-on-error: true
            uses: ./.github/actions/build-windows
            with:
                archive-name: v8_windows_x64

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: v8_windows_x64
                path: |
                    *.tar.xz
                    *.7z
                retention-days: 7

    commit:
        name: Commit to repository
        runs-on: ubuntu-latest
        needs: build-win64
        steps:
          - name: Checkout This Repo
            uses: actions/checkout@v4

          - name: Write Current Commit Hash
            run:


          - name: Download Archives
            uses: actions/download-artifact@v4
            with:
                path: artifact

          - name: Commit
            run: echo 1
