name: Build on Windows

on:
    workflow_call:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                clean: true
                fetch-depth: 1

          - name: Set Git Configs
            shell: cmd
            run: |
                git config branch.autosetupmerge always
                git config branch.autosetuprebase always
                git config --global core.autocrlf false
                git config --global core.filemode false
                git config --global core.longpaths true
                git config --global core.preloadindex true
                git config --global core.fscache true

          - name: Checkout Depot Tools
            uses: newkdev/setup-depot-tools@v1.0.1

          - name: Checkout V8 Source Code
            shell: cmd
            run: |
                set DEPOT_TOOLS_WIN_TOOLCHAIN=0
                mkdir v8
                cd v8
                fetch v8
                gclient sync

          - name: Build V8 Using GM
            shell: cmd
            run: |
                python v8\tools\dev\gm.py x64.release

          - name: Archive V8
            shell: pwsh
            run: .\native\archive.bat "v8_windows_x64"
        
          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: v8_windows_x64
                path: |
                    *.tar.xz
                    *.7z
                retention-days: 7