name: Build on Windows

on:
    workflow_call:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                submodules: true
                clean: true
                fetch-depth: 1

        #  - name: Restore V8 Cache
        #    uses: actions/cache@v4
        #    with:
        #        path: |
        #            v8
        #            .gclient_entries
        #            .gclient_previous_sync_commits
        #            .cipd
        #        key: ${{runner.os}}-${{runner.arch}}:libv8:v8:${{hashFiles('**/VERSION')}}
        #        restore-keys: |
        #            ${{runner.os}}-${{runner.arch}}:libv8:v8:

        #  - name: Restore SCCache
        #    uses: actions/cache@v4
        #    with:
        #        path: .sccache
        #        key: ${{runner.os}}-${{runner.arch}}:libv8:sccache:${{github.run_number}}
        #        restore-keys: |
        #            ${{runner.os}}-${{runner.arch}}:libv8:sccache:

        #  - name: Setup Bootstrap Tools
        #    shell: cmd
        #    run: .\depot_tools\bootstrap\win_tools.bat

        #  - name: Setup Scoop
        #    uses: MinoruSekine/setup-scoop@v4

        #  - name: Setup Build Tools
        #    shell: pwsh
        #    run: |
        #        scoop install sccache
        #        $sccacheDir = "$Env:GITHUB_WORKSPACE`\.sccache"
        #        New-Item -Path "$sccacheDir" -ItemType Directory -Force
        #        Write-Output "SCCACHE_DIR=$sccacheDir" | Out-File -FilePath "$Env:GITHUB_ENV" -Encoding utf8

          - name: Checkout V8 Source Code
            shell: cmd
            run: |
                cd depot_tools
                git reset --hard
                git config branch.autosetupmerge always
                git config --global core.autocrlf false
                git config --global core.filemode false
                git config --global core.longpaths true
                git config --global core.preloadindex true
                git config --global core.fscache true
                git config branch.autosetuprebase always
          - name: test1
            shell: cmd
            run: |
                cd depot_tools
                dir
                .\gclient.bat
                
          - name: test2
            shell: cmd
            run: |
                cd depot_tools
                mkdir v8
                cd v8
                ..\fetch.bat v8

          - name: test3
            shell: cmd
            run: |
                cd depot_tools\v8\v8
                ..\gclient.bat sync
          - name: Setup GM
            shell: pwsh
            run: |
                ls
                python depot_tools\v8\v8\tools\dev\gm.py x64.release
        
          - name: Download V8 Source
            shell: cmd
            run: .\native\v8_download.bat

          - name: Compile V8
            shell: cmd
            run: .\native\v8_compile.bat
      
          - name: Show SCCache Status
            shell: pwsh
            run: sccache --show-stats
      
          - name: Setup Developer Command Prompt
            uses: ilammy/msvc-dev-cmd@v1
      
          - name: Test V8
            shell: cmd
            run: .\native\v8_test.bat
        
          - name: Archive V8
            shell: pwsh
            run: .\native\archive.bat "v8_windows_x64"
        
          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: v8_windows_x64
                path: |
                    *.tar.xz
                    *.7z
                retention-days: 7