name: Check V8 Tags

on:
    schedule:
        - cron: "0 4 * * *"
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        outputs:
            update: ${{steps.should_update.outputs.update}}
        steps:

          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                ref: main

          - name: Get Last Built Commit
            id: current_commit
            uses: juliangruber/read-file-action@v1
            with:
                path: ./COMMIT

          - name: Clone V8
            run:  |
                git clone --depth 1 --no-checkout --tags https://chromium.googlesource.com/v8/v8.git
                git fetch --tags
                cd v8

          - name: Determine Should Update
            id: should_update
            run: |
                current_commit="${{steps.current_commit.outputs.content}}"
                current_commit="${current_commit%"${current_commit##*[![:space:]]}"}"
                latest_commit=$(git rev-list --tags --max-count=1)
                echo "Current commit: $current_commit"
                echo "Latest commit: $latest_commit"
                if [ "$current_commit" = "$latest_commit" ]; then
                    echo "update=false" >> $GITHUB_OUTPUT
                    echo "not update"
                else
                    echo "update=true" >> $GITHUB_OUTPUT
                    echo "update"
                fi

    build-win64:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: cherryridge/v8-monolith-builds/.github/workflows/build-v8-win64.yml@main

    build-linux:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: cherryridge/v8-monolith-builds/.github/workflows/build-v8-linux.yml@main

    build-macos:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: cherryridge/v8-monolith-builds/.github/workflows/build-v8-macos.yml@main