name: Main Task

on:
    schedule:
        - cron: "0 4 */7 * *"
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        outputs:
            update: ${{steps.should_update.outputs.update}}
            latest_commit: ${{steps.should_update.outputs.latest_commit}}
        steps:

          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                ref: main

          - name: Get Last Built Commit
            id: current_commit
            uses: juliangruber/read-file-action@v1
            with:
                path: ./COMMIT

          - name: Determine Should Update
            id: should_update
            run: |
                current_commit="${{steps.current_commit.outputs.content}}"
                current_commit="${current_commit%"${current_commit##*[![:space:]]}"}"
                latest_commit=$(curl -s https://api.github.com/repos/v8/v8/tags | jq -r '.[12].commit.sha')
                echo "Current commit: $current_commit"
                echo "Latest commit: $latest_commit"
                echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT
                if [ "$current_commit" = "$latest_commit" ]; then
                    echo "update=false" >> $GITHUB_OUTPUT
                    echo "Build skipped."
                else
                    echo "update=true" >> $GITHUB_OUTPUT
                    echo "Starting build process."
                fi

    build-windows:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: ./.github/workflows/build-v8-windows.yml
        with:
            commit: ${{needs.check.outputs.latest_commit}}

    build-linux:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: ./.github/workflows/build-v8-linux.yml
        with:
            commit: ${{needs.check.outputs.latest_commit}}

    build-macos:
        needs: check
        if: needs.check.outputs.update == 'true'
        uses: ./.github/workflows/build-v8-macos.yml
        with:
            commit: ${{needs.check.outputs.latest_commit}}

    update-commit:
        runs-on: ubuntu-latest
        needs: [check, build-linux, build-macos, build-windows]
        permissions:
            contents: write
        env:
            LATEST_COMMIT: ${{needs.check.outputs.latest_commit}}
        steps:

          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                ref: main

          - name: Configure Git
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          - name: Update Commit File
            run: |
                set +o noclobber
                echo "$LATEST_COMMIT" > ./COMMIT

          - name: Commit Changes
            run: |
                git add COMMIT
                git commit -m "Automated: Update COMMIT to $LATEST_COMMIT"
                git push